// <auto-generated />
using System;
using AuctionSystem.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuctionSystem.Api.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20260426201216_SeparateCategoryFromAuction")]
    partial class SeparateCategoryFromAuction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuctionSystem.Api.Domain.Entities.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StartingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CurrentPrice = 82m,
                            Description = "Classic 35mm film camera in good condition.",
                            EndDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 1,
                            StartDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 50m,
                            Title = "Vintage Camera"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CurrentPrice = 120m,
                            Description = "Used mountain bike, aluminum frame.",
                            EndDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 1,
                            StartDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 120m,
                            Title = "Mountain Bike"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CurrentPrice = 800m,
                            Description = "High‑performance laptop with RTX GPU.",
                            EndDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 1,
                            StartDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 800m,
                            Title = "Gaming Laptop"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CurrentPrice = 90m,
                            Description = "Waterproof smartwatch with GPS.",
                            EndDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 1,
                            StartDate = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 90m,
                            Title = "Smartwatch"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CurrentPrice = 60m,
                            Description = "Beginner‑friendly acoustic guitar.",
                            EndDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 1,
                            StartDate = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 60m,
                            Title = "Acoustic Guitar"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            CurrentPrice = 40m,
                            Description = "Ergonomic chair with lumbar support.",
                            EndDate = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 1,
                            StartDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 40m,
                            Title = "Office Chair"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CurrentPrice = 30m,
                            Description = "Portable speaker with deep bass.",
                            EndDate = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 1,
                            StartDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 30m,
                            Title = "Bluetooth Speaker"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 6,
                            CurrentPrice = 70m,
                            Description = "10‑piece stainless steel cookware.",
                            EndDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 1,
                            StartDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 70m,
                            Title = "Cookware Set"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CurrentPrice = 150m,
                            Description = "Quadcopter with HD camera.",
                            EndDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 1,
                            StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 150m,
                            Title = "Drone"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 7,
                            CurrentPrice = 25m,
                            Description = "Handmade genuine leather wallet.",
                            EndDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 1,
                            StartDate = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 25m,
                            Title = "Leather Wallet"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            CurrentPrice = 20m,
                            Description = "LED lamp with adjustable brightness.",
                            EndDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 1,
                            StartDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 20m,
                            Title = "Desk Lamp"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CurrentPrice = 210m,
                            Description = "Great for rock and blues.",
                            EndDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 2,
                            StartDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 150m,
                            Title = "Electric Guitar"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            CurrentPrice = 200m,
                            Description = "Automatic espresso machine.",
                            EndDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 2,
                            StartDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 200m,
                            Title = "Coffee Machine"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CurrentPrice = 180m,
                            Description = "10‑inch tablet for work and play.",
                            EndDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 2,
                            StartDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 180m,
                            Title = "Tablet"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CurrentPrice = 50m,
                            Description = "Lightweight running shoes.",
                            EndDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 2,
                            StartDate = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 50m,
                            Title = "Running Shoes"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            CurrentPrice = 220m,
                            Description = "144Hz gaming monitor.",
                            EndDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 2,
                            StartDate = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 220m,
                            Title = "Monitor 27\""
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CurrentPrice = 70m,
                            Description = "Mechanical keyboard with RGB.",
                            EndDate = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 2,
                            StartDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 70m,
                            Title = "Keyboard"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CurrentPrice = 300m,
                            Description = "Unlocked Android phone.",
                            EndDate = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 2,
                            StartDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 300m,
                            Title = "Smartphone"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 8,
                            CurrentPrice = 90m,
                            Description = "4‑person waterproof tent.",
                            EndDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 2,
                            StartDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 90m,
                            Title = "Camping Tent"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            CurrentPrice = 35m,
                            Description = "Polarized UV protection.",
                            EndDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 2,
                            StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 35m,
                            Title = "Sunglasses"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 9,
                            CurrentPrice = 45m,
                            Description = "Durable travel backpack.",
                            EndDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 2,
                            StartDate = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 45m,
                            Title = "Backpack"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            CurrentPrice = 25m,
                            Description = "Fast‑boil stainless steel kettle.",
                            EndDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 2,
                            StartDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 25m,
                            Title = "Electric Kettle"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            CurrentPrice = 600m,
                            Description = "Lightweight carbon frame.",
                            EndDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 3,
                            StartDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 500m,
                            Title = "Road Bike"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            CurrentPrice = 400m,
                            Description = "55‑inch UHD Smart TV.",
                            EndDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 3,
                            StartDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 400m,
                            Title = "4K TV"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 15,
                            CurrentPrice = 350m,
                            Description = "Foldable scooter with long battery life.",
                            EndDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 3,
                            StartDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 350m,
                            Title = "Electric Scooter"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            CurrentPrice = 80m,
                            Description = "HEPA filter air purifier.",
                            EndDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 3,
                            StartDate = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 80m,
                            Title = "Air Purifier"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 16,
                            CurrentPrice = 60m,
                            Description = "Cordless drill with accessories.",
                            EndDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 3,
                            StartDate = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 60m,
                            Title = "Electric Drill"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 7,
                            CurrentPrice = 90m,
                            Description = "Insulated waterproof jacket.",
                            EndDate = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 3,
                            StartDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 90m,
                            Title = "Winter Jacket"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            CurrentPrice = 120m,
                            Description = "Noise‑cancelling over‑ear headphones.",
                            EndDate = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 3,
                            StartDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 120m,
                            Title = "Wireless Headphones"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 5,
                            CurrentPrice = 150m,
                            Description = "Ergonomic gaming chair.",
                            EndDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 3,
                            StartDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 150m,
                            Title = "Gaming Chair"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 12,
                            CurrentPrice = 35m,
                            Description = "Set of 5 bestselling cookbooks.",
                            EndDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 3,
                            StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 35m,
                            Title = "Cookbook Collection"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 1,
                            CurrentPrice = 45m,
                            Description = "Tracks steps, sleep, and heart rate.",
                            EndDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 3,
                            StartDate = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 45m,
                            Title = "Fitness Tracker"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 6,
                            CurrentPrice = 20m,
                            Description = "Wooden organizer for office supplies.",
                            EndDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 3,
                            StartDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 20m,
                            Title = "Desk Organizer"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            CurrentPrice = 155m,
                            Description = "Retro turntable with speakers.",
                            EndDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 4,
                            StartDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 100m,
                            Title = "Vinyl Record Player"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 5,
                            CurrentPrice = 250m,
                            Description = "Comfortable 3‑seat sofa.",
                            EndDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 4,
                            StartDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 250m,
                            Title = "Sofa"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            CurrentPrice = 180m,
                            Description = "1080p home cinema projector.",
                            EndDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 4,
                            StartDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 180m,
                            Title = "Projector"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 2,
                            CurrentPrice = 300m,
                            Description = "Skis, poles, and boots.",
                            EndDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 4,
                            StartDate = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 300m,
                            Title = "Ski Set"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 6,
                            CurrentPrice = 70m,
                            Description = "Indoor smokeless grill.",
                            EndDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 4,
                            StartDate = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 70m,
                            Title = "Electric Grill"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 9,
                            CurrentPrice = 120m,
                            Description = "3‑piece travel luggage.",
                            EndDate = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 4,
                            StartDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 120m,
                            Title = "Luggage Set"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 10,
                            CurrentPrice = 40m,
                            Description = "Rechargeable toothbrush with timer.",
                            EndDate = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 4,
                            StartDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 40m,
                            Title = "Electric Toothbrush"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 11,
                            CurrentPrice = 30m,
                            Description = "Collection of 10 classic board games.",
                            EndDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 4,
                            StartDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 30m,
                            Title = "Board Game Set"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 6,
                            CurrentPrice = 35m,
                            Description = "Portable ceramic heater.",
                            EndDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 4,
                            StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 35m,
                            Title = "Electric Heater"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 14,
                            CurrentPrice = 25m,
                            Description = "Compact vacuum for car interiors.",
                            EndDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 4,
                            StartDate = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 25m,
                            Title = "Car Vacuum"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 2,
                            CurrentPrice = 20m,
                            Description = "Non‑slip yoga mat.",
                            EndDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 4,
                            StartDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 20m,
                            Title = "Yoga Mat"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            CurrentPrice = 55m,
                            Description = "Adjustable aluminum stand.",
                            EndDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 5,
                            StartDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 30m,
                            Title = "Laptop Stand"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 6,
                            CurrentPrice = 60m,
                            Description = "700W compact microwave.",
                            EndDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 5,
                            StartDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 60m,
                            Title = "Microwave Oven"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            CurrentPrice = 80m,
                            Description = "20W practice amplifier.",
                            EndDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 5,
                            StartDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 80m,
                            Title = "Electric Guitar Amp"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 1,
                            CurrentPrice = 55m,
                            Description = "Controls smart devices.",
                            EndDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 5,
                            StartDate = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 55m,
                            Title = "Smart Home Hub"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 6,
                            CurrentPrice = 65m,
                            Description = "Oil‑less cooking appliance.",
                            EndDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 5,
                            StartDate = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 65m,
                            Title = "Air Fryer"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 13,
                            CurrentPrice = 85m,
                            Description = "Softbox lighting set for studio work.",
                            EndDate = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 5,
                            StartDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 85m,
                            Title = "Photography Lighting Kit"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 10,
                            CurrentPrice = 40m,
                            Description = "Rechargeable shaver with precision blades.",
                            EndDate = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 5,
                            StartDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 40m,
                            Title = "Electric Shaver"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 3,
                            CurrentPrice = 55m,
                            Description = "1TB USB 3.0 external drive.",
                            EndDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 5,
                            StartDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 55m,
                            Title = "Portable Hard Drive"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 14,
                            CurrentPrice = 15m,
                            Description = "Dashboard mount for smartphones.",
                            EndDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 5,
                            StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 15m,
                            Title = "Car Phone Holder"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            CurrentPrice = 45m,
                            Description = "Heated blanket with adjustable settings.",
                            EndDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 5,
                            StartDate = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 45m,
                            Title = "Electric Blanket"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 3,
                            CurrentPrice = 25m,
                            Description = "Ergonomic mouse with long battery life.",
                            EndDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 5,
                            StartDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartingPrice = 25m,
                            Title = "Wireless Mouse"
                        });
                });

            modelBuilder.Entity("AuctionSystem.Api.Domain.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 55m,
                            AuctionId = 1,
                            PlacedAt = new DateTime(2026, 5, 8, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 6
                        },
                        new
                        {
                            Id = 2,
                            Amount = 60m,
                            AuctionId = 1,
                            PlacedAt = new DateTime(2026, 5, 8, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 7
                        },
                        new
                        {
                            Id = 3,
                            Amount = 68m,
                            AuctionId = 1,
                            PlacedAt = new DateTime(2026, 5, 8, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 8
                        },
                        new
                        {
                            Id = 4,
                            Amount = 75m,
                            AuctionId = 1,
                            PlacedAt = new DateTime(2026, 5, 8, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 9
                        },
                        new
                        {
                            Id = 5,
                            Amount = 82m,
                            AuctionId = 1,
                            PlacedAt = new DateTime(2026, 5, 8, 23, 50, 0, 0, DateTimeKind.Unspecified),
                            UserId = 10
                        },
                        new
                        {
                            Id = 6,
                            Amount = 160m,
                            AuctionId = 12,
                            PlacedAt = new DateTime(2026, 5, 8, 21, 40, 0, 0, DateTimeKind.Unspecified),
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Amount = 170m,
                            AuctionId = 12,
                            PlacedAt = new DateTime(2026, 5, 8, 22, 20, 0, 0, DateTimeKind.Unspecified),
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Amount = 185m,
                            AuctionId = 12,
                            PlacedAt = new DateTime(2026, 5, 8, 22, 50, 0, 0, DateTimeKind.Unspecified),
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Amount = 195m,
                            AuctionId = 12,
                            PlacedAt = new DateTime(2026, 5, 8, 23, 20, 0, 0, DateTimeKind.Unspecified),
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Amount = 210m,
                            AuctionId = 12,
                            PlacedAt = new DateTime(2026, 5, 8, 23, 45, 0, 0, DateTimeKind.Unspecified),
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            Amount = 520m,
                            AuctionId = 23,
                            PlacedAt = new DateTime(2026, 5, 8, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 6
                        },
                        new
                        {
                            Id = 12,
                            Amount = 540m,
                            AuctionId = 23,
                            PlacedAt = new DateTime(2026, 5, 8, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 7
                        },
                        new
                        {
                            Id = 13,
                            Amount = 560m,
                            AuctionId = 23,
                            PlacedAt = new DateTime(2026, 5, 8, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 8
                        },
                        new
                        {
                            Id = 14,
                            Amount = 580m,
                            AuctionId = 23,
                            PlacedAt = new DateTime(2026, 5, 8, 23, 15, 0, 0, DateTimeKind.Unspecified),
                            UserId = 9
                        },
                        new
                        {
                            Id = 15,
                            Amount = 600m,
                            AuctionId = 23,
                            PlacedAt = new DateTime(2026, 5, 8, 23, 40, 0, 0, DateTimeKind.Unspecified),
                            UserId = 10
                        },
                        new
                        {
                            Id = 16,
                            Amount = 110m,
                            AuctionId = 34,
                            PlacedAt = new DateTime(2026, 5, 8, 21, 20, 0, 0, DateTimeKind.Unspecified),
                            UserId = 6
                        },
                        new
                        {
                            Id = 17,
                            Amount = 120m,
                            AuctionId = 34,
                            PlacedAt = new DateTime(2026, 5, 8, 22, 10, 0, 0, DateTimeKind.Unspecified),
                            UserId = 7
                        },
                        new
                        {
                            Id = 18,
                            Amount = 135m,
                            AuctionId = 34,
                            PlacedAt = new DateTime(2026, 5, 8, 22, 40, 0, 0, DateTimeKind.Unspecified),
                            UserId = 8
                        },
                        new
                        {
                            Id = 19,
                            Amount = 145m,
                            AuctionId = 34,
                            PlacedAt = new DateTime(2026, 5, 8, 23, 10, 0, 0, DateTimeKind.Unspecified),
                            UserId = 9
                        },
                        new
                        {
                            Id = 20,
                            Amount = 155m,
                            AuctionId = 34,
                            PlacedAt = new DateTime(2026, 5, 8, 23, 35, 0, 0, DateTimeKind.Unspecified),
                            UserId = 10
                        },
                        new
                        {
                            Id = 21,
                            Amount = 35m,
                            AuctionId = 45,
                            PlacedAt = new DateTime(2026, 5, 8, 21, 50, 0, 0, DateTimeKind.Unspecified),
                            UserId = 6
                        },
                        new
                        {
                            Id = 22,
                            Amount = 40m,
                            AuctionId = 45,
                            PlacedAt = new DateTime(2026, 5, 8, 22, 25, 0, 0, DateTimeKind.Unspecified),
                            UserId = 7
                        },
                        new
                        {
                            Id = 23,
                            Amount = 45m,
                            AuctionId = 45,
                            PlacedAt = new DateTime(2026, 5, 8, 22, 50, 0, 0, DateTimeKind.Unspecified),
                            UserId = 8
                        },
                        new
                        {
                            Id = 24,
                            Amount = 50m,
                            AuctionId = 45,
                            PlacedAt = new DateTime(2026, 5, 8, 23, 25, 0, 0, DateTimeKind.Unspecified),
                            UserId = 9
                        },
                        new
                        {
                            Id = 25,
                            Amount = 55m,
                            AuctionId = 45,
                            PlacedAt = new DateTime(2026, 5, 8, 23, 50, 0, 0, DateTimeKind.Unspecified),
                            UserId = 10
                        });
                });

            modelBuilder.Entity("AuctionSystem.Api.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Home"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Outdoors"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Games"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Tools"
                        });
                });

            modelBuilder.Entity("AuctionSystem.Api.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Doe",
                            Username = "jdoe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alice",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Smith",
                            Username = "asmith"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Brian",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Jackson",
                            Username = "bjackson"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chloe",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Wilson",
                            Username = "cwilson"
                        },
                        new
                        {
                            Id = 5,
                            Name = "David",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Thomas",
                            Username = "dthomas"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Emma",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Clark",
                            Username = "eclark"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Frank",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Martin",
                            Username = "fmartin"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Grace",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "White",
                            Username = "gwhite"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Henry",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Walker",
                            Username = "hwalker"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Isabella",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Johnson",
                            Username = "ijohnson"
                        },
                        new
                        {
                            Id = 11,
                            Name = "James",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Lewis",
                            Username = "jlewis"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Karen",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Roberts",
                            Username = "kroberts"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Liam",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "King",
                            Username = "lking"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mia",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Green",
                            Username = "mgreen"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Noah",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Wright",
                            Username = "nwright"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Olivia",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Allen",
                            Username = "oallen"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Paul",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Phillips",
                            Username = "pphillips"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Quinn",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Campbell",
                            Username = "qcampbell"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Ryan",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Turner",
                            Username = "rturner"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Sophia",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Moore",
                            Username = "smoore"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Thomas",
                            PasswordHash = "$2a$11$1oqokiyY1uOg3IY.YYD6Yu6v65h.MwNfAr4jRhGvfUpxuB9HaPROO",
                            Surname = "Ward",
                            Username = "tward"
                        });
                });

            modelBuilder.Entity("AuctionSystem.Api.Domain.Entities.Auction", b =>
                {
                    b.HasOne("AuctionSystem.Api.Domain.Entities.Category", "Category")
                        .WithMany("Auctions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuctionSystem.Api.Domain.Entities.User", "Owner")
                        .WithMany("Auctions")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AuctionSystem.Api.Domain.Entities.Bid", b =>
                {
                    b.HasOne("AuctionSystem.Api.Domain.Entities.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionSystem.Api.Domain.Entities.User", "User")
                        .WithMany("Bids")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionSystem.Api.Domain.Entities.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("AuctionSystem.Api.Domain.Entities.Category", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("AuctionSystem.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
